/*
 * This source file was generated by the Gradle 'init' task
 */
package com.box.utils;
;
import net.sourceforge.argparse4j.ArgumentParsers;
import net.sourceforge.argparse4j.impl.Arguments;
import net.sourceforge.argparse4j.inf.ArgumentParser;

public class Reporter {

    public static void main(String[] args) {

        ArgumentParser parser = ArgumentParsers.newFor("reporter").build();
        // Add Argument
        parser.addArgument("-c", "--config")
                .required(true)
                .help("Client configuration file path")
                .type(Arguments.fileType().verifyCanRead());
        parser.addArgument("-r", "--report")
                .required(true)
                .help("Report Definition File")
                .type(Arguments.fileType().verifyCanRead());
        parser.addArgument("-o", "--output")
                .required(true)
                .help("Output file path")
                .type(Arguments.fileType().verifyCanCreate());
        
        // Process the input file and generate report
    }
}
